### PR TITLE
Fix flag parsing, add verbose mode, add multistream recusion handling

### LINKED ISSUE #2: Output of mss
Would be nice if this tool out put like this:

```
< incoming line
> outgoing line
...
```

example

```
$ mss-nc 127.0.0.1 4001
< /multistream/1.0.0
> /multistream/1.0.0
> ls
< /plaintext/1.0.0
> /plaintext/1.0.0
< /plaintext/1.0.0
> ls
< /yamux/1.0.0
< /spdy/1.0.0
< /singlemux/1.0.0
> /singlemux/1.0.0
< /singlemux/1.0.0
> ls
< /dht/1.0.0
< /identify/1.0.0
< /bitswap/1.0.0
< /ping/1.0.0
```

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves #2

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM, thanks @Kubuxu!! :+1:

**Comment by jbenet** [comment]
There's a bug here.

```
mss-nc -v 127.0.0.1 4001
> /multistream/1.0.0
< /multistream/1.0.0
> ls
```

entering `ls` produces no output

**Comment by Kubuxu** [comment]
Works over here:

```
mss-nc -v localhost 4001
> /multistream/1.0.0
< /multistream/1.0.0
> ls 
/secio/1.0.0
> 
```

Are you sure that you confirmed ls with new line?

**Comment by jbenet** [comment]
I typed: "ls\n" do I need two newlines or something?

**Comment by Kubuxu** [comment]
I just typed `ls` and pressed enter.

**Comment by jbenet** [comment]
@Kubuxu: found the problem, i think it fails if `na` is returned. try:

```
$ ipfs daemon --disable-transport-encryption &
$ mss-nc -v 127.0.0.1 4001
> /multistream/1.0.0
< /multistream/1.0.0
> foo
< na
ls
ls
:(
```

**Comment by Kubuxu** [comment]
It is so because if you type in unhandled data, ls and multiprotocol strings are handled, then it switches to binary mode.

I can make it to keep being in multistream mode but I don't know if it is proper handling.

**Pull request merged**
